### PR TITLE
RE Crypto : assignment 1 (changes made) and Crypto-Session 5&6-Assignment-Phase-1 - Vandana

### PR DESCRIPTION
**Pull request by valkyr13**

### CODE REVIEW

**Comment by mahirjain25** [comment]
@valkyr13 , please look into making changes in the RE Assignment as mentioned in this thread. Your PR is almost ready to merge.

**Comment by valkyr13** [comment]
I have made the suggested changes to the  RE Assignment  2 days ago

**Comment by mahirjain25** [comment]
@suraj44, this one is almost done. A quick review of the issue you highlighted earlier, please.

**Comment by suraj44** [comment]
So palindrome works perfectly now
However, digital root does not seem to be working correctly. @valkyr13 at 'exit_prog' which register is supposed to be holding the value of the digital root in the code you've written?

**Comment by valkyr13** [comment]
@suraj44 the final value of the digital root is stored in 'r9'.

**Comment by suraj44** [comment]
Really appreciate the effort

**Comment by valkyr13** [comment]
@suraj44 thanks and  I appreciate your help too!

**Pull request merged**
