### PR TITLE
Assignments 1 & 2

### PR DESCRIPTION
**Pull request by the-nakki**

### CODE REVIEW

**Comment by mahirjain25** [comment]
Why are there so many commits on this PR?
@suraj44 @ShashankP19 @adwait1-G , we need to try and clear this up.

**Comment by suraj44** [comment]
Really not sure what commit 1902af5 is for
@mahirjain25 there are some commits for your assignment as well but this PR is really really messy.

**Comment by mahirjain25** [comment]
@the-nakki , can you move out your folders, do a git pull, then add them, commit and push again?
It will make life a lot simpler. There are some commits we are not able to keep track of.

**Comment by suraj44** [comment]
I tried running `palindrome.asm` and `factorial.asm`, but both run into segmentation faults. It's clear that you haven't tried executing these programs on NASM. The logic of what you've done seems right but if you had problems writing assembly language, you could have contacted us and we would have been happy helping you resolve your errors. Further, your files are all over the place, they are not in the specified directory but you've put them in the root folder. I think the best thing to do would be to take all the relevant files that you intend to submit, copy them elsewhere, delete the SummerProjects18 folder locally and clone it again. That way your commit history will be clean and it will make sure there are no unnecessary as well(like the .i and .o files in the Session2/Assignment folder that you have created). Again, if you want some help, please feel free to tell us the issues you're facing

**Comment by the-nakki** [comment]
So you're saying I should save all the work that I've to submit, delete my
fork of SummerProjects18 as well as the local folder and then fork it again?

**Comment by the-nakki** [comment]
# Regarding so many commits and an overall messy repo, I took some time to
fully understand how to use git. Often i'd type git commit praying to god
it worked and also kept pressing the 'pull request' button as i knew very
little about what I was doing, so sorry about that.
# Due to some peculiar reason all the assembly programs I wrote ran into
segfaults , to the point where I have absolutely no clue on what's wrong.
So i just posted the codes hoping you guys could tell me what's wrong.
# Along with deleting my local copy of SummerProjects18 and recloning it
should I also delete my fork of it and make a new one ?

**Pull request closed without merging**
