### PR TITLE
RE-Crypto assignment 1 & 2

### PR DESCRIPTION
**Pull request by Shreyaar19**

### CODE REVIEW

**Comment by Shreyaar19** [comment]
I have added files for assignment 2,I will do the corrections in assignment 1 and update them.

**Comment by suraj44** [comment]
@adwait1-G review assignment 2 which in the latest commit

**Comment by suraj44** [comment]
@Shreyaar19 any updates on assignment 1?

**Comment by Shreyaar19** [comment]
yes, I'll upload the changes by 12 tonight

**Comment by suraj44** [comment]
In the digital root question for the input 10123, the output is 4 which is wrong.

**Pull request merged**
